version: '2'
exclude_patterns:
  - '**/*spec.ts'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 75
          similar-code:
            config:
              threshold: 95
