version: '2'
exclude_patterns:
  - '**/*spec.ts'
plugins:
  duplication:
    enabled: false
    config:
      languages:
        - typescript
    checks:
      similar-code:
        config:
          threshold: 75
